'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SYSERPEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SYSERPEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Tbl_ADQ_Tipocompra() As DbSet(Of Tbl_ADQ_Tipocompra)
    Public Overridable Property Tbl_Areas() As DbSet(Of Tbl_Areas)
    Public Overridable Property Tbl_Articulo() As DbSet(Of Tbl_Articulo)
    Public Overridable Property Tbl_Clientes() As DbSet(Of Tbl_Clientes)
    Public Overridable Property Tbl_CTComprobantes() As DbSet(Of Tbl_CTComprobantes)
    Public Overridable Property Tbl_Departamento() As DbSet(Of Tbl_Departamento)
    Public Overridable Property Tbl_Medidas() As DbSet(Of Tbl_Medidas)
    Public Overridable Property Tbl_Pais() As DbSet(Of Tbl_Pais)
    Public Overridable Property Tbl_Producto() As DbSet(Of Tbl_Producto)
    Public Overridable Property Tbl_Proveedor() As DbSet(Of Tbl_Proveedor)
    Public Overridable Property Tbl_Servicios() As DbSet(Of Tbl_Servicios)
    Public Overridable Property Tbl_Solicitante() As DbSet(Of Tbl_Solicitante)
    Public Overridable Property Tbl_Solicitudes_Enc() As DbSet(Of Tbl_Solicitudes_Enc)
    Public Overridable Property Tbl_Tasacambio() As DbSet(Of Tbl_Tasacambio)
    Public Overridable Property Tbl_TipoIdentificacion() As DbSet(Of Tbl_TipoIdentificacion)
    Public Overridable Property Tbl_TipoPersona() As DbSet(Of Tbl_TipoPersona)
    Public Overridable Property Tbl_Ubicacion() As DbSet(Of Tbl_Ubicacion)
    Public Overridable Property Tbl_Usuario() As DbSet(Of Tbl_Usuario)

End Class
