'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Proveedor
    Public Property CCODPVE As String
    Public Property CRAZON As String
    Public Property CNOMBRE As String
    Public Property CDIRECC As String
    Public Property CCIUDAD As String
    Public Property CTELEFO As String
    Public Property CCONTAC As String
    Public Property CCARGO As String
    Public Property CREFERE As String
    Public Property CMAIL As String
    Public Property CNUMRUC As String
    Public Property CESTADO As String
    Public Property ITIPPVE As Nullable(Of Integer)
    Public Property IEXEN_IR As Nullable(Of Integer)
    Public Property IEXEN_ALMA As Nullable(Of Integer)
    Public Property CCUENTA As String

End Class
