'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Solicitudes_Enc
    Public Property No_Solicitud As String
    Public Property Tipo_Compra As String
    Public Property Tipo_Compra_L As String
    Public Property Tipo_Uso As String
    Public Property Cod_Solicitante As String
    Public Property Cod_Departamento As String
    Public Property Cod_Depto_Destino As String
    Public Property Aprobado As Nullable(Of Boolean)
    Public Property Cod_Aprobado As String
    Public Property Cod_Analista As String
    Public Property Fecha_Asigna_Analista As Nullable(Of Date)
    Public Property Estatus As Nullable(Of Decimal)
    Public Property Estado As String
    Public Property Observacion As String
    Public Property Fecha_Solicitud As Nullable(Of Date)
    Public Property Fecha_Crea As Nullable(Of Date)

End Class
