'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Clientes
    Public Property IdCliente As Integer
    Public Property Nombre As String
    Public Property Apellidos As String
    Public Property FechaNacimiento As Date
    Public Property IdTipoIdentificacion As Integer
    Public Property Cedula As String
    Public Property IdTipoPersona As Integer
    Public Property IdPais As Integer
    Public Property Correo As String
    Public Property Telefono_Casa As String
    Public Property Telefono_Celular As String
    Public Property Estado As Boolean
    Public Property FechaRegistro As Date
    Public Property FechaModificacion As Nullable(Of Date)

End Class
