'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Producto
    Public Property Cod_Producto As String
    Public Property Descripcion As String
    Public Property Descripcion_L As String
    Public Property Cod_UM As String
    Public Property Uscrea As String
    Public Property Fecha_Crea As Nullable(Of Date)

End Class
