'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tbl_Articulo
    Public Property Id_Articulo As Integer
    Public Property Cod_Activo As String
    Public Property Descripcion As String
    Public Property Marca As String
    Public Property Modelo As String
    Public Property Serie As String
    Public Property Dimensiones As String
    Public Property Asignado As String
    Public Property Cod_Area As String
    Public Property Cod_Ubicacion_F As String
    Public Property Estado As String
    Public Property Fecha As Nullable(Of Date)

End Class
